version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - npm install

build: off

before_test:
  - node -v
  - npm -v
  - node webpack -p

test_script:
  - tmp\testing

after_test:
  - 7z a -r dbs.zip tmp geodet

artifacts:
  - path: "*.zip"
    name: Built applications
