# Default parameters

# Расстояние между деталями
gap: 15

# Расстояние от детали до края листа
border: 15

# Допустимые вращения (0, 1, 90, 180)
rotate: 1

# Допустимые отражения
mirror: 1

# Скорость (6, 60, 600)
# CAT_FAST_SPEED_MODE: 6,
# CAT_RECOMMENDED_SPEED_MODE: 60
# CAT_COMPLETE_SPEED_MODE: 600
time: 6
