name: DBS

on:
  push:


jobs:
  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ubuntu-latest
    needs: before

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  always

      - run:  npm install

      - name: Build
        run:  npm start

      - name: Assemble artifacts
        run:  7z a -r dbs.zip tmp geodet

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: ./*.zip

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundle
          path: .

      - run: unzip *.zip

      - run: ./testing
        working-directory: tmp

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'publish'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          # fetch-depth: 2
          ref: www # gh-pages
          path: www

      - uses: actions/download-artifact@v2
        with:
          name: bundle
          path: .

      - name: UnPack
        run: |
          unzip -jod scripts *.zip

      - name: RePack
        working-directory: scripts
        run: |
          zip ../dbs-util *.bat -x testing.bat

      - name: Make git commit message
        run: |
          git log -1 --format="%h: %s" > .commit

      - name: Build
        working-directory: www
        run: |
          rm -rf json-schema
          cp -rf ../json-schema .
          cp -f ../*.md .
          cp -f ../dbs-util.zip .
          git add --all
          git config user.email "none"
          git config user.name "GitHub Pages Publisher"
          git diff-index --quiet HEAD || git commit -F ../.commit
          git push
