name: test

on:
  push:

jobs:
  before:
    runs-on: windows-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  test:
    runs-on: windows-latest
    needs: before

    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  always

      - name: Install packages
        run:  npm install

      - name: Build
        run:  npm start

      - name: Test
        run:  tmp\testing

      - name: Save artifacts
        run:  7z a -r dbs.zip tmp geodet

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: ./*.zip

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'publish'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          # fetch-depth: 2
          ref: www # gh-pages
          path: www

      - uses: actions/download-artifact@v2
        with:
          name: bundle
          path: .

      - name: UnPack
        run: |
          unzip -jod scripts *.zip

      - name: RePack
        working-directory: scripts
        run: |
          zip ../utils *.bat -x testing.bat

      - name: Show
        run: |
          ls -lR
